# Generated by Django 5.0.3 on 2024-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
