# Generated by Django 5.0.3 on 2024-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
