# Generated by Django 5.0.3 on 2024-04-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_purchases_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='category_id',
        ),
    ]
